### ISSUE TITLE
VSCO không chạy

### ISSUE THREAD

**Issue by Jeffeditae** [hcsavn/Quantumult-X#1]

**Comment by hcsavn** [comment]
tui đã thử lại và vẫn chạy ông ạ, à VSCO là phải bật thủ công trong mục rewrite rồi mới vào app bấm restore nha. Tại VSCO host restore nó trùng với 1 vài app khác nên chỉ bật khi nào restore thôi, restore xong thì tắt đi để tránh xung đột app khác.

**Comment by Jeffeditae** [comment]
![Uploading 155486264...]

Vẫn không được anh ạ

**Comment by hcsavn** [comment]
ông có thể gửi tui clip cách ông restore VSCO được k?
