### ISSUE TITLE
restore apollo + md clock  fall

### ISSUE THREAD

**Issue by XXXGITHUB777** [hcsavn/Quantumult-X#2]
english badly ,sorry

use quantumult x  and rewrite
"rni film  success " ✓

but

"nicegram  apollo  mdclock  fall" ×

what happen T_T

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by hcsavn** [comment]
• With MD Clock, you must enable MD Clock in Rewrite before restore.

Rewrite -> Link ->  Enable MD Clock

• With Apollo, do not restore in Apollo Pro, restore in Apollo Ultra

• With Nicegram, you need use Nicegram Messenger Plus (it's the new application of the developer Nicegram)
Link: https://apps.apple.com/vn/app/nicegram-messenger-plus/id1608870673?l=vi

Then, you can restore it in:
Settings -> Nicegram -> Restore Premium
